version: 2.1

orbs:
  tools: replikativ/clj-tools@0

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          context: dockerhub-deploy
      - tools/format:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/unittest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/cljstest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/integrationtest-postgresql:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/build:
          context: dockerhub-deploy          
          jarname: "hasch"
          requires:
            - tools/setup
      - tools/deploy-snapshot:
          jarname: "hasch"
          context: clojars-deploy
          context: dockerhub-deploy
          filters:
            branches:
              only: development
          requires:
            - tools/setup
            - tools/format
            - tools/unittest
            - tools/cljstest
            - tools/integrationtest-postgresql
            - tools/build
      - tools/deploy-release:
          jarname: "hasch"
          context: clojars-deploy
          context: dockerhub-deploy
          filters:
            branches:
              only: master
          requires:
            - tools/setup
            - tools/format
            - tools/unittest
            - tools/cljstest
            - tools/integrationtest-postgresql
            - tools/build
